[package]
name = "out_in_corners"
version = "0.1.0"
authors = ["non7247 <funi_funi@nifty.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bgc = { path = "../bgc" }
